import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
            crossOrigin="anonymous"
            referrerpolicy="no-referrer"
          />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
          />
        </Head>
        {/* <Navbar /> */}
        <main className={styles.main}>
          <div>
            {/* <div className={styles.title}> */}
            <h1>Rita Uzoma.</h1>
            {/* </div> */}
            <div className={styles.description}>
              <h4>Frontend Developer and writer </h4>
            </div>

            {/* links */}
            <div className={styles.links}>
              <ul>
                <li>
                  <Link href="/about">About</Link>
                </li>
                <li>Resume</li>
                <li>Articles</li>
                <li>
                  <Link href="/portfolio">Portfolio</Link>
                </li>
              </ul>
            </div>
            <div className={styles.socials}>
              <i className="fa-brands fa-2xl fa-github"></i>
              <i className="fa-brands fa-2xl fa-linkedin"></i>
              <i className="fa-brands fa-2xl fa-twitter"></i>
              <i className="fa-brands fa-2xl fa-instagram"></i>
              <i className="fa-regular fa-2xl fa-envelope"></i>
            </div>
          </div>

          <div className={styles.image_section}>
            <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
              <path
                fill="#FF0066"
                d="M64.1,-50.8C80.2,-30.9,88.4,-4.4,83.1,19.1C77.9,42.7,59.1,63.2,36.1,74C13,84.8,-14.4,85.7,-36.8,75.3C-59.2,64.9,-76.6,43.2,-81.6,19.2C-86.6,-4.8,-79.2,-31,-63.5,-50.8C-47.9,-70.6,-23.9,-83.9,0,-84C24,-84,48,-70.7,64.1,-50.8Z"
                transform="translate(100 100)"
              />
            </svg>
          </div>
        </main>
        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by
            <span className={styles.logo}>
              <Image
                src="/images/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer> */}
      </div>
    </>
  );
}
